### PR TITLE
Merge upstream changes

### PR DESCRIPTION
**Pull request by chrisbc**
need to resolve conflicts

### CODE REVIEW

**Comment by chrisbc** [comment]
@ElenaManea has asked that this project be updated from the upstream gem:master. So this PR is the result.

As I am not a contributor and have not any visibility of the impacts, so @thingbaijam and @g-weatherill I've taken the liberty of requesting your review please :). There are a few dangling branches and PRs, which will likely need more attention if they're ever going to make it onto master.

And can someone resolve the conflict on `doc/sphinx/openquake.hazardlib.gsim.rst` (hopefully thi is trivial).

**Review by g-weatherill — APPROVED** [review]
Looks good to me. Is it probably easier to fix the conflicts on your own branch rather than me attempting to push to it. It is just one of the doc files.

**Review by thingbaijam — APPROVED** [review]
Okay - quite a large number of commits; going with @g-weatherill. Approved @chrisbc .

**Comment by chrisbc** [comment]
> Okay - quite a large number of commits; going with @g-weatherill. Approved @chrisbc .

@ElenaManea It seems graeme and Kiran are both happy to merge this, but I'm afraid  don't have time to fix the minor merge conflict. Are you able to do this please (see instructions above) . Then then you can go ahead and merge this PR :)

**Comment by g-weatherill** [comment]
@chrisbc @ElenaManea Can you update us on the status of this? Both @thingbaijam and I have approved this PR three weeks ago but this is still not merged. In the meantime, as you can see there have been a huge number of new commits in the main OQ-engine (they are working on a massive refactoring of the GMPEs, so this is not trivial) and I am now getting double notifications for each commit.

Is there a problem fixing the conflicts?

**Pull request closed without merging**
